version: "3.9"

services:
  redis:
    image: redis
    container_name: redis-server

  build-worker:
    build: ./build-worker
    container_name: build-worker
    entrypoint: [ "true" ]
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis-server

  build-orchestrator:
    build: ./build-orchestrator
    container_name: build-orchestrator
    environment:
      - PORT=3001
      - REDIS_HOST=redis-server
      - BIND_PATH=C:/personal-projects/secrets
    ports:
      - "3001:3001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
  proxy-server:
    build: ./proxy-server
    container_name: proxy-server
    environment:
      - PORT=3002
      - CDN_URL=${CDN_URL}
    ports:
      - "3002:3002"
