services:
  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  build-worker:
    build:
      context: ./build-worker
    image: build-worker
    container_name: build-worker
    entrypoint: ["true"]
    depends_on:
      - redis

  build-orchestrator:
    build:
      context: ./build-orchestrator
    image: build-orchestrator
    container_name: build-orchestrator
    env_file:
      - .env.orchestrator
    ports:
      - "3001:3001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
      - postgres

  proxy-server:
    build:
      context: ./proxy
    image: proxy
    container_name: proxy
    env_file:
      - .env.proxy
    ports:
      - "3002:3002"
    depends_on:
      - postgres

  web:
    build:
      context: ./web
      args:
        - NEXT_PUBLIC_ORCHESTRATOR_URL=${NEXT_PUBLIC_ORCHESTRATOR_URL}
    image: web
    container_name: web
    ports:
      - "3000:3000"
    env_file:
      - .env.web
    depends_on:
      - postgres
      - redis
      - build-orchestrator
      - proxy-server

volumes:
  pgdata:
