services:
  redis:
    image: redis
    container_name: redis-server
  postgres:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  build-worker:
    build: ./build-worker
    container_name: build-worker
    entrypoint: [ "true" ]
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis-server

  build-orchestrator:
    build: ./build-orchestrator
    container_name: build-orchestrator
    environment:
      - PORT=3001
      - REDIS_HOST=redis-server
      - BIND_PATH=C:/personal-projects/secrets
      - DATABASE_URL=postgresql://myuser:mypassword@postgres-db:5432/mydb
    ports:
      - "3001:3001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
  proxy-server:
    build: ./proxy
    container_name: proxy
    environment:
      - PORT=3002
      - CDN_URL=${CDN_URL}
      - DATABASE_URL=postgresql://myuser:mypassword@postgres-db:5432/mydb
    ports:
      - "3002:3002"
volumes:
  pgdata: