name: CI/CD pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps: 
      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /root/Vexl
            docker compose -f docker-compose.prod.yml down
            git pull
            docker compose -f docker-compose.prod.yml up -d postgres redis
            sleep 10
            docker compose -f docker-compose.prod.yml up -d --build
